In [ ]:
import torch

In [ ]:
torch.empty(size=(2,2,3))

tensor([[[9.9190e-14, 3.0632e-41, 5.0447e-44],
         [0.0000e+00,        nan, 6.4460e-44]],

        [[1.3788e-14, 3.6423e-06, 2.0699e-19],
         [3.3738e-12, 7.4086e+28, 6.9397e+22]]])

In [ ]:
torch.ones(size=(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.ones(size=(2,3))*3

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [ ]:
torch.arange(4)

tensor([0, 1, 2, 3])

In [ ]:
x = torch.empty(size=(2,2))
print(type(x))
print(x.dtype)

<class 'torch.Tensor'>
torch.float32


In [ ]:
torch.linspace(start=1, end = 10, steps= 20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [ ]:
import numpy as np
a = np.arange(6)

In [ ]:
t = torch.tensor(a)
type(t)

torch.Tensor

##OR


In [ ]:
t1 = torch.from_numpy(a)
type(t)

torch.Tensor

Back to numpy



In [ ]:
t.numpy()

array([0, 1, 2, 3, 4, 5])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.diag(torch.tensor([1,2,3,4]))

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])

In [ ]:
t = torch.rand(size=(2,2))
t

tensor([[0.6421, 0.8179],
        [0.4125, 0.3308]])

In [ ]:
torch.diag(t)

tensor([0.6421, 0.3308])

##Tensor Operations


In [ ]:
x = torch.ones(size=(3,3))
y = torch.ones(size=(3,3))*4
print(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [ ]:
z = torch.empty(size=(3,3))

In [ ]:
torch.add(x,y,out=z)
z

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [ ]:
z= torch.add(x,y)
z

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [ ]:
z = x+y
z

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

Inplace functions ends with _

In [ ]:
x.add_(y)
x

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [ ]:
batch = 32
m = 2
n = 3
p = 4

In [ ]:
x = torch.ones(size=(batch,m,n))
y = torch.ones(size=(batch,n,m))

In [ ]:
torch.bmm(x,y).shape

torch.Size([32, 2, 2])

In [ ]:
t = torch.tensor([1,2,3,4])
t.shape

torch.Size([4])

In [ ]:
t.unsqueeze(axis=0)

tensor([[1, 2, 3, 4]])

In [ ]:
t.unsqueeze(axis=1)

tensor([[1],
        [2],
        [3],
        [4]])

In [ ]:
t.unsqueeze(axis=1).squeeze()

tensor([1, 2, 3, 4])

In [ ]:
t = torch.arange(15)
t

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
t.view(3,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
t.view(1,3,5)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]])

In [ ]:
tensor = torch.linspace(0,10,24).reshape(2,3,4)
tensor

tensor([[[ 0.0000,  0.4348,  0.8696,  1.3043],
         [ 1.7391,  2.1739,  2.6087,  3.0435],
         [ 3.4783,  3.9130,  4.3478,  4.7826]],

        [[ 5.2174,  5.6522,  6.0870,  6.5217],
         [ 6.9565,  7.3913,  7.8261,  8.2609],
         [ 8.6957,  9.1304,  9.5652, 10.0000]]])

In [ ]:
tensor[0]

tensor([[0.0000, 0.4348, 0.8696, 1.3043],
        [1.7391, 2.1739, 2.6087, 3.0435],
        [3.4783, 3.9130, 4.3478, 4.7826]])

In [ ]:
tensor[0][:,:2]

tensor([[0.0000, 0.4348],
        [1.7391, 2.1739],
        [3.4783, 3.9130]])

In [ ]:
tensor.sum(axis=0)

tensor([[ 5.2174,  6.0870,  6.9565,  7.8261],
        [ 8.6957,  9.5652, 10.4348, 11.3043],
        [12.1739, 13.0435, 13.9130, 14.7826]])

In [ ]:
tensor.sum(axis=1)

tensor([[ 5.2174,  6.5217,  7.8261,  9.1304],
        [20.8696, 22.1739, 23.4783, 24.7826]])

In [ ]:
tensor.sum(axis=2)

tensor([[ 2.6087,  9.5652, 16.5217],
        [23.4783, 30.4348, 37.3913]])